apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: '*'
      kind: '*'
      name: v1beta1.metrics.k8s.io
      jsonPointers:
        - /spec/insecureSkipTLSVerify
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.*
    helm:
      valuesObject:
        replicas: 2
        tls:
          type: cert-manager
        apiService:
          insecureSkipTLSVerify: false
