apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
spec:
  project: default
  destination:
    name: in-cluster
    namespace: kube-vip
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://kube-vip.github.io/helm-charts/
    chart: kube-vip
    targetRevision: 0.*
    helm:
      valuesObject:
        config:
          address: 10.5.0.1
        env:
          vip_arp: 'false'
          bgp_enable: 'true'
          cp_enable: 'true'
          bgp_as: "65000"
          bgp_peeras: "65000"
          bgp_peers: 10.0.0.1:65000::false,10.5.1.2:65000::false,10.5.2.1:65000::false,10.5.3.4:65000::false
        envValueFrom:
          bgp_routerid:
            fieldRef:
              fieldPath: status.podIP
        tolerations:
          - effect: 'NoSchedule'
            operator: 'Exists'
