apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip-cloud-provider
spec:
  project: default
  destination:
    name: in-cluster
    namespace: kube-vip
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://kube-vip.github.io/helm-charts/
    chart: kube-vip-cloud-provider
    targetRevision: 0.*
    helm:
      valuesObject:
        cm:
          data:
            cidr-global: 10.5.0.128/25
