prowlarr:
  image:
    repository: lscr.io/linuxserver/prowlarr
  livenessProbe:
    httpGet:
      path: /ping
  readinessProbe:
    httpGet:
      path: /ping
  ingress:
    hostname: prowlarr.lexrj.com
