radarr:
  image:
    repository: lscr.io/linuxserver/radarr
  livenessProbe:
    httpGet:
      path: /ping
  readinessProbe:
    httpGet:
      path: /ping
  multimedia:
    enabled: true
  ingress:
    hostname: radarr.lexrj.com
