apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "application.name" . }}
  labels:
{{/*    name: ""*/}}
    {{- include "application.labels" . | nindent 4 }}
  {{- with .Values.statefulSet.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.statefulSet.config.storageClassName }}
        storageClassName: {{ .Values.statefulSet.config.storageClassName }}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.statefulSet.config.storage }}
  serviceName: {{ include "application.name" . }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.statefulSet.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "application.labels" . | nindent 8 }}
        {{- with .Values.statefulSet.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 120
      {{- with .Values.statefulSet.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "application.serviceAccountName" . }}
      {{- with .Values.statefulSet.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.statefulSet.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.statefulSet.image.repository }}:{{ .Values.statefulSet.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.statefulSet.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.statefulSet.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.statefulSet.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
            {{- if .Values.multimedia.enabled }}
            - name: multimedia
              mountPath: /multimedia
            {{- end }}
            {{- if .Values.backups.enabled }}
            - name: backups
              mountPath: /backups
            {{- end }}
            {{- with .Values.statefulSet.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- if or .Values.multimedia.enabled .Values.backups.enabled .Values.statefulSet.volumes }}
      volumes:
        {{- if .Values.multimedia.enabled }}
        - name: multimedia
          {{- .Values.multimedia.volume | default .Values.global.multimedia | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.backups.enabled }}
        - name: backups
          {{ .Values.backups.volume | default .Values.global.backups | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.statefulSet.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.statefulSet.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.statefulSet.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.statefulSet.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
