apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '-99999'
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: x
      helm:
        parameters:
          - name: global.domain
            value: 'argocd.lexrj.com'
          - name: redis-ha.enabled
            value: 'true'
          - name: server.certificate.enabled
            value: 'true'
          - name: server.certificate.issuer.kind
            value: 'ClusterIssuer'
          - name: server.certificate.issuer.name
            value: 'cloudflare'
          - name: server.ingress.enabled
            value: 'true'
          - name: server.ingress.tls
            value: 'true'
          - name: server.ingressGrpc.enabled
            value: 'true'
          - name: server.ingressGrpc.tls
            value: 'true'
        valuesObject:
          configs:
            params:
              server.insecure: true
    - repoURL: https://github.com/RegentOfOrigin/argocd.git
      path: appprojects
      targetRevision: HEAD
    - repoURL: https://github.com/RegentOfOrigin/argocd.git
      path: applications
      targetRevision: HEAD
