apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  syncPolicy:
#    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://charts.jetstack.io/
    chart: cert-manager
    targetRevision: x
    helm:
      parameters:
        - name: replicaCount
          value: 2
        - name: cainjector.replicaCount
          value: 2
        - name: installCRDs
          value: true
        - name: webhook.replicaCount
          value: 2
      valuesObject:
        extraObjects:
          - |
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: cloudflare
            spec:
              acme:
                email: regentoforigin@proton.me
                server: https://acme-v02.api.letsencrypt.org/directory
                privateKeySecretRef:
                  name: cloudflare-account-key
                solvers:
                  - dns01:
                      cloudflare:
                        apiTokenSecretRef:
                          name: cloudflare-api-token-secret
                          key: api-token
                      dnsZones:
                        - 'lexrj.com'
                        - 'regentoforigin.me'
          - |
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: selfsigned
            spec:
              selfSigned: {}