apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/
    chart: csi-driver-nfs
    targetRevision: x
    helm:
      parameters:
        - name: kubeletDir
          value: /var/snap/microk8s/common/var/lib/kubelet
        - name: controller.defaultOnDeletePolicy
          value: 'archive'
        - name: storageClass.create
          value: 'true'
        - name: feature.enableFSGroupPolicy
          value: 'true'
        #- name: feature.enableInlineVolume
        #  value: 'true'
      valuesObject:
        storageClass:
          name: nfs
          annotations:
            storageclass.kubernetes.io/is-default-class: 'true'
          parameters:
            server: nfs-server.default.svc.cluster.local
            share: /tank/kubernetes
            subDir: '${pvc.metadata.namespace}/${pvc.metadata.name}'
            onDelete: 'archive'
            # kubectl create -n kube-system secret generic mount-options --from-literal mountOptions='nfsvers=4.2,hard'
            #csi.storage.k8s.io/provisioner-secret-name: 'mount-options'
            #csi.storage.k8s.io/provisioner-secret-namespace: 'default'
          volumeBindingMode: Immediate
          mountOptions:
            - nfsvers=4.2
