apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/
    chart: csi-driver-nfs
    targetRevision: x
    helm:
      parameters:
        - name: controller.defaultOnDeletePolicy
          value: Archive
      valuesObject:
        storageClass:
          create: true
          name: nfs
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
          parameters:
            server: tartarus.local
            share: /tank/kubernetes
          reclaimPolicy: Retain
          volumeBindingMode: WaitForFirstConsumer
          mountOptions: []
