apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/
    chart: csi-driver-nfs
    targetRevision: x
    helm:
      parameters:
        - name: controller.defaultOnDeletePolicy
          value: 'Archive'
        - name: storageClass.create
          value: 'true'
      valuesObject:
        storageClass:
          name: nfs
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
          parameters:
            # Create service nfs-server.default.svc.cluster.local
            server: tartarus.cluster.local
            # Create better mount location
            share: /tank/kubernetes
#            csi.storage.k8s.io/provisioner-secret-name: "mount-options"
#            csi.storage.k8s.io/provisioner-secret-namespace: "default"
          reclaimPolicy: Retain
          volumeBindingMode: WaitForFirstConsumer
#          mountOptions:
#            - nfsvers=4.1
