apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  source:
    repoURL: https://github.com/RegentOfOrigin/argo-cd.git
    path: manifests/home-assistant
    targetRevision: HEAD
