apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/RegentOfOrigin/argocd
    path: applications
    targetRevision: HEAD
