apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/RegentOfOrigin/argocd
    path: applications
    targetRevision: HEAD
