apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  syncPolicy:
#    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
#      - Force=true
#      - Replace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: x
    helm:
      valuesObject:
        controller:
          admissionWebhooks:
            certManager:
              enabled: true
          hostPort:
            enabled: true
          ingressClassResource:
            default: true
          replicaCount: 2
          publishService:
            enabled: false
          extraArgs:
            publish-status-address: 127.0.0.1
  #      defaultBackend:
  #        enabled: false
  #        name: defaultbackend
  #        replicaCount: 2
  #        image:
  #          image: registry.k8s.io/defaultbackend-amd64
