apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: x
    helm:
      parameters:
        - name: controller.service.type
          value: 'ClusterIP'
        - name: controller.admissionWebhooks.certManager.enabled
          value: 'true'
        - name: controller.hostPort.enabled
          value: 'true'
        - name: controller.ingressClassResource.default
          value: 'true'
        - name: controller.kind
          value: 'DaemonSet'
        - name: controller.publishService.enabled
          value: 'false'
#        - name: defaultBackend.enabled
#          value: false
#        - name: defaultBackend.name
#          value: defaultbackend
#        - name: defaultBackend.replicaCount
#          value: 2
#        - name: defaultBackend.image.allowPrivilegeEscalation
#          value: false
#        - name: defaultBackend.image.image
#          value: defaultbackend-amd64
#        - name: defaultBackend.image.runAsGroup
#          value: 65534
#        - name: defaultBackend.image.runAsNonRoot
#          value: true
#        - name: defaultBackend.image.runAsUser
#          value: 65534
#        - name: defaultBackend.image.tag
#          value: 1.5
      valuesObject:
        controller:
          extraArgs:
            publish-status-address: '127.0.0.1'
