apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-media-server
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  syncPolicy:
#    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    chart: plex-media-server
    targetRevision: x
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.ingressClassName
          value: 'nginx'
        - name: ingress.url
          value: 'plex.lexrj.com'
        - name: serviceAccount.automountServiceAccountToken
          value: 'true'
      valuesObject:
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: cloudflare
        extraVolumes:
          - name: dev-dri
            hostPath:
              path: /dev/dri
              type: Directory
          - name: multimedia
            hostPath:
              path: /tank/multimedia
              type: Directory
        extraVolumeMounts:
          - name: dev-dri
            mountPath: /dev/dri
          - name: multimedia
            mountPath: /multimedia
        nodeSelector:
          node.lexrj.com/role: storage
        tolerations:
          - key: "node.lexrj.com/role"
            operator: "Equal"
            value: "storage"
