apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-media-server
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  syncPolicy:
#    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    chart: plex-media-server
    targetRevision: x
    helm:
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: nginx
          url: "plex.lexrj.com"
          annotations:
            cert-manager.io/cluster-issuer: cloudflare
          initContainer:
            script: |
              if [ -d /config/Library ]; then
                if [ -e /config/DBRepair.sh ]; then
                  exit 0
                fi
                echo "You done fucked up"
                exit 1
              fi
              cp -r /old-config/* /config/*
        nodeSelector:
          lexrj.com/role: nas
        extraVolumes:
          - name: dev-dri
            hostPath:
              path: /dev/dri
              type: Directory
          - name: multimedia
            hostPath:
              path: /tank/multimedia
              type: Directory
          - name: old-config
            nfs:
              server: tartarus.internal
              path: /tank/kubernetes/plex-backup
              readOnly: true
        extraVolumeMounts:
          - name: dev-dri
            mountPath: /dev/dri
          - name: multimedia
            mountPath: /multimedia
          - mountPath: /old-config
            name: old-config
