apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starr
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  syncPolicy:
#    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: starr
  source:
    repoURL: https://github.com/RegentOfOrigin/argocd.git
    path: charts/starr
    targetRevision: HEAD
    helm:
      valuesObject:
        global:
          ingress:
            whitelistSourceRange: 10.0.0.0/8
          multimedia:
            nfs:
              path: /tank/multimedia
          backups:
            nfs:
              path: /tank/multimedia
        radarr:
          ingress:
            enabled: true
            hostname: "radarr.lexrj.com"
        sonarr:
          ingress:
            enabled: true
            hostname: "sonarr.lexrj.com"
        whisparr:
          image:
            tag: v3
          ingress:
            enabled: true
            hostname: "whisparr.lexrj.com"
        prowlarr:
          ingress:
            enabled: true
            hostname: "prowlarr.lexrj.com"
        bazarr:
          enabled: true
          ingress:
            enabled: true
            hostname: "bazarr.lexrj.com"
        recyclarr: {}
        overseerr:
          ingress:
            enabled: true
            hostname: "overseerr.lexrj.com"
