apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sabnzbd.service.type }}
  ports:
    - port: {{ .Values.sabnzbd.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sabnzbd.selectorLabels" . | nindent 4 }}
