{{- if .Values.sabnzbd.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sabnzbd
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
  {{- with .Values.sabnzbd.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.sabnzbd.serviceAccount.automount }}
{{- end }}
