apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sabnzbd
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
spec:
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.sabnzbd.storageClassName }}
        storageClassName: {{ .Values.sabnzbd.storageClassName }}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.sabnzbd.storage }}
  serviceName: sabnzbd
  selector:
    matchLabels:
      {{- include "sabnzbd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.sabnzbd.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sabnzbd.labels" . | nindent 8 }}
        {{- with .Values.sabnzbd.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: sabnzbd
      containers:
        - name: main
          image: "{{ .Values.sabnzbd.image.repository }}:{{ .Values.sabnzbd.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.sabnzbd.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.sabnzbd.service.port }}
              protocol: TCP
          {{- with .Values.sabnzbd.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.sabnzbd.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /config
            {{- with .Values.sabnzbd.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.sabnzbd.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sabnzbd.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
