apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus
  annotations:
    argocd.argoproj.io/sync-wave: '-10000'
spec:
  project: default
  destination:
    name: in-cluster
    namespace: multus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://github.com/RegentOfOrigin/argocd.git
    targetRevision: HEAD
    path: manifests/multus
