{{- if .Values.qbittorrent.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
  {{- with .Values.qbittorrent.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.qbittorrent.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.qbittorrent.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.qbittorrent.ingress.path }}
            pathType: {{ .Values.qbittorrent.ingress.pathType }}
            backend:
              service:
                name: qbittorrent
                port:
                  number: {{ .Values.qbittorrent.service.port }}
  {{- if .Values.qbittorrent.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.qbittorrent.ingress.hostname }}
      secretName: qbittorrent-server-tls
  {{- end }}
{{- end }}
