apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.qbittorrent.service.type }}
  ports:
    - port: {{ .Values.qbittorrent.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}
