apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.sabnzbd.storageClassName }}
        storageClassName: {{ .Values.sabnzbd.storageClassName }}
      {{- end }}
        resources:
          requests:
            storage: {{ .Values.sabnzbd.storage }}
  serviceName: qbittorrent
  selector:
    matchLabels:
      {{- include "qbittorrent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.qbittorrent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qbittorrent.labels" . | nindent 8 }}
        {{- with .Values.qbittorrent.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: qbittorrent
      containers:
        - name: main
          image: "{{ .Values.qbittorrent.image.repository }}:{{ .Values.qbittorrent.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.qbittorrent.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.qbittorrent.service.port }}
              protocol: TCP
          {{- with .Values.qbittorrent.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.qbittorrent.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.qbittorrent.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /config
            {{- with .Values.qbittorrent.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: { }
      {{- with .Values.qbittorrent.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.qbittorrent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
