apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-media-server
  annotations:
    argocd.argoproj.io/sync-wave: '10'
    link.argocd.argoproj.io/application: 'https://plex.lexrj.com'
spec:
  project: default
  destination:
    name: in-cluster
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    chart: plex-media-server
    targetRevision: 0.*
    helm:
      valuesObject:
        ingress:
          enabled: true
          url: plex.lexrj.com
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: cloudflare

        extraEnv:
          ADVERTISE_IP: https://plex.lexrj.com:443
        serviceAccount:
          automountServiceAccountToken: true
        extraVolumes:
          - name: dev-dri
            hostPath:
              path: /dev/dri
              type: Directory
          - name: multimedia
            hostPath:
              path: /tank/multimedia
              type: Directory
        extraVolumeMounts:
          - name: dev-dri
            mountPath: /dev/dri
          - name: multimedia
            mountPath: /multimedia
        nodeSelector:
          node.lexrj.com/role: 'storage'
        tolerations:
          - key: 'node.lexrj.com/role'
            operator: 'Equal'
            value: 'storage'
