apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server
  annotations:
    argocd.argoproj.io/sync-wave: '-10000'
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://github.com/RegentOfOrigin/argocd.git
    targetRevision: HEAD
    path: manifests/nfs
