apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-dhcp
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "macvlan",
    "mode": "bridge",
    "ipam": {
      "type": "host-local",
      "subnet": "10.5.0.64/26",
      "gateway": "10.0.0.1"
    }
  }'
