apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-dhcp
spec:
  config: '{"type": "macvlan", "mode": "bridge", "ipam": {"type": "dhcp", "daemonSocketPath": "/var/snap/microk8s/current/var/run/cni/dhcp.sock"}}'
