apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: docker-apps
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  syncPolicy:
    applicationsSync: create-update
  generators:
    - list:
        elements:
          - name: kometa
          - name: tautulli
        template:
          metadata: {}
          spec:
            project: default
            destination:
              namespace: plex
    - list:
        elements:
          - name: stash
        template:
          metadata: {}
          spec:
            project: default
            destination:
              namespace: stash
    - list:
        elements:
          - name: radarr
          - name: sonarr
          - name: whisparr
          - name: prowlarr
          - name: bazarr
          - name: recyclarr
          - name: overseerr
        template:
          metadata: {}
          spec:
            project: default
            destination:
              namespace: starr
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      destination:
        name: in-cluster
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
      source:
        repoURL: https://github.com/RegentOfOrigin/argocd.git
        path: charts/application
        targetRevision: HEAD
        helm:
          ignoreMissingValueFiles: true
          valuesObject:
            nameOverride: '{{ .name }}'
          valueFiles:
            - values.yaml
            - values-{{ .name }}.yaml
