apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: '-1000'
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://charts.jetstack.io/
    chart: cert-manager
    targetRevision: 1.*
    helm:
      valuesObject:
        replicaCount: 2
        cainjector:
          replicaCount: 2
        webhook:
          replicaCount: 2
        crds:
          enabled: true
          keep: true
        extraObjects:
          - |
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: cloudflare
            spec:
              acme:
                email: regentoforigin@proton.me
                server: https://acme-v02.api.letsencrypt.org/directory
                privateKeySecretRef:
                  name: cloudflare-account-key
                solvers:
                  - dns01:
                      cloudflare:
                        apiTokenSecretRef:
                          name: cloudflare-api-token-secret
                          key: api-token
            ---
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: selfsigned
            spec:
              selfSigned: {}
