apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: meta
spec:
  description: Meta project for bootstrapping Argo CD
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
