qbittorrent:
  image:
    repository: ghcr.io/hotio/qbittorrent
  env:
    - name: PUID
      value: '1000'
    - name: PGID
      value: '1000'
  podSecurityContext: {}
  securityContext: {}
  service:
    port: 8080
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
  multimedia:
    enabled: true

sabnzbd:
  image:
    repository: ghcr.io/hotio/sabnzbd
  env:
    - name: PUID
      value: '1000'
    - name: PGID
      value: '1000'
  podSecurityContext: {}
  securityContext: {}
  service:
    port: 8080
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
  multimedia:
    enabled: true
