apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-99999"
spec:
  project: meta
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: x
      helm:
        parameters:
          - name: global.domain
            value: argocd.lexrj.com
          - name: redis-ha.enabled
            value: 'true'
          - name: configs.params.server.insecure
            value: 'true'
        valuesObject:
          server:
            certificate:
              enabled: true
              issuer:
                kind: ClusterIssuer
                name: cloudflare
            ingress:
              enabled: true
              tls: true
            ingressGrpc:
              enabled: true
              tls: true
    - repoURL: https://github.com/RegentOfOrigin/argocd.git
      targetRevision: HEAD
      path: argocd/
