apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: meta
spec:
  description: Meta project for bootstrapping Argo CD
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta
spec:
  project: meta
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/RegentOfOrigin/argocd.git
    path: applications
    targetRevision: HEAD
