apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: meta
spec:
  description: Meta project for bootstrapping Argo CD
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta
  annotations:
    argocd.argoproj.io/sync-wave: "-9999"
spec:
  project: meta
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/RegentOfOrigin/argocd
      path: argocd
      targetRevision: HEAD
    - repoURL: https://github.com/RegentOfOrigin/argocd
      path: applications
      targetRevision: HEAD
