image:
  repository: stashapp/stash
env:
  USER: stash
  STASH_PORT: '8080'
  STASH_CONFIG_FILE: /config/config.yml
  STASH_GENERATED: /config/generated/
  STASH_METADATA: /config/metadata/
  STASH_CACHE: /config/cache/
  STASH_STASH: /multimedia/Whisparr/
nodeSelector:
  node.lexrj.com/role: storage
tolerations:
  - key: node.lexrj.com/role
    operator: Equal
    value: storage
