image:
  registry: lscr.io
  repository: linuxserver/sonarr
multimedia:
  type: hostPath
nodeName: tartarus
resources:
  requests:
    memory: "500Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1"