apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  annotations:
    argocd.argoproj.io/sync-wave: '-1000'
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts/
    chart: csi-driver-nfs
    targetRevision: '4.*'
    helm:
      valuesObject:
        kubeletDir: /var/snap/microk8s/common/var/lib/kubelet
        controller:
          defaultOnDeletePolicy: archive
        feature:
          enableFSGroupPolicy: true
          enableInlineVolume: true
        storageClass:
          create: true
          name: nfs
          annotations:
            storageclass.kubernetes.io/is-default-class: 'true'
          parameters:
            server: nfs-server.default.svc.cluster.local
            share: /tank/kubernetes
            subDir: '${pvc.metadata.namespace}/${pvc.metadata.name}'
            onDelete: archive
            # kubectl create -n kube-system secret generic mount-options --from-literal mountOptions='nfsvers=4.2,hard'
            #csi.storage.k8s.io/provisioner-secret-name: 'mount-options'
            #csi.storage.k8s.io/provisioner-secret-namespace: 'default'
          volumeBindingMode: Immediate
          mountOptions:
            - nfsvers=4.2
