apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
spec:
  type: ExternalName
  externalName: homeassistant.local:8123
