apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | indent 4 }}
  {{- end }}
spec:
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.config.storage }}
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ .Values.macvlanAttachment | squote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "home-assistant.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: main
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}{{ include "home-assistant.image.tag" . | nospace }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range $envName, $envValue := .Values.env }}
            - name: {{ $envName | quote }}
              value: {{ $envValue | quote }}
            {{- end }}
            {{- range $envName, $envValue := .Values.envFrom }}
            - name: {{ $envName | quote }}
              valueFrom:
                 {{- $envValue | toYaml | nindent 16 }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.config.mountPath }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- range $name, $value := .Values.addons }}
        {{- if not $value.enabled }}{{ continue }}{{ end }}
        - name: {{ $name }}
          {{- with $value }}
          {{- with $value.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
          imagePullPolicy: {{ $value.image.pullPolicy }}
          ports:
            - name: {{ $name }}
              containerPort: {{ $value.service.port }}
              protocol: TCP
          env:
            {{- range $envName, $envValue := $value.env }}
            - name: {{ $envName | quote }}
              value: {{ $envValue | quote }}
            {{- end }}
            {{- range $envName, $envValue := $value.envFrom }}
            - name: {{ $envName | quote }}
              valueFrom:
                 {{- $envValue | toYaml | nindent 16 }}
            {{- end }}
          {{- with $value.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $value.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: {{ $.Values.config.mountPath }}
              subPath: addons/{{ $name }}
            {{- with $value.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeName }}
      nodeName: {{ . }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
