macvlanAttachment: multus/macvlan

securityContext:
  privileged: true
  capabilities:
    add: [ "NET_BROADCAST" ]

volumes:
  - name: dev-skyconnect
    hostPath:
      path: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_523dbab6b596ed1197bac098a7669f5d-if00-port0
  - name: dev-sonoff-zigbee
    hostPath:
      path: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_523dbab6b596ed1197bac098a7669f5d-if00-port0

volumeMounts:
  - name: dev-skyconnect
    mountPath: /dev/ttyUSB0
    mountPropagation: Bidirectional
  - name: dev-sonoff-zigbee
    mountPath: /dev/ttyACM0
    mountPropagation: Bidirectional

nodeSelector: {}

nodeName: 'aether'

tolerations: []

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cloudflare
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  hostname: 'homeassistant.lexrj.com'
