# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: 'ghcr.io/home-assistant/home-assistant'
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 'stable'

config:
  mountPath: /config
  # Backups will eat this up. Manage your backups carefully
  storage: 2Gi

macvlanAttachment: macvlan

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}

securityContext: {}

annotations: {}

env: []

envFrom: []

# This is to set up the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe: {}

readinessProbe: {}

# Additional volumes on the output StatefulSet definition.
volumes: []

# Additional volumeMounts on the output StatefulSet definition.
volumeMounts: []

nodeName: ''

nodeSelector: {}

tolerations: []

affinity: {}

terminationGracePeriodSeconds: ''

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # If not set a name is generated using the fullname template
  name: ''

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8123

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  annotations: {}

  # -- Defines which ingress controller will implement the resource
  className: ''

  # -- server hostname. addons will be added as subdomains, e.g. homeassistant.example.com
  # @default -- `''`
  ## Note: Supports use of custom Helm templates
  hostname: ''

  # -- Additional ingress paths
  # @default -- `[]`
  ## Note: Supports use of custom Helm templates
  extraPaths: []

  # -- Additional ingress rules
  # @default -- `[]`
  ## Note: Supports use of custom Helm templates
  extraRules: []

  # -- Additional TLS configuration
  # @default -- `[]`
  extraTls: []

resources: {}

addons:
  esphome:
    enabled: false
    image:
      repository: 'ghcr.io/esphome/esphome'
      # This sets the pull policy for images.
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: 'latest'

    # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
    service:
      # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
      port: 6052

    securityContext: {}

    env: []

    envFrom: []

    # This is to set up the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
    livenessProbe: {}

    readinessProbe: {}

    # Additional volumeMounts on the addon container.
    volumeMounts: []
