apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  annotations:
    link.argocd.argoproj.io/application: 'https://homeassistant.lexrj.com'
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  destination:
    name: in-cluster
    namespace: home-assistant
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://github.com/RegentOfOrigin/argocd.git
    path: charts/home-assistant
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-lexrj.yaml
