apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/sync-wave: '-100'
spec:
  project: default
  destination:
    name: in-cluster
    namespace: nginx
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.*
    helm:
      valuesObject:
        controller:
          config:
            whitelist-source-range: 10.0.0.0/8
          service:
            annotations:
              kube-vip.io/loadbalancerIPs: 10.5.0.2
            externalTrafficPolicy: Local
          admissionWebhooks:
            certManager:
              enabled: true
#          hostPort:
#            enabled: true
          ingressClassResource:
            default: true
          kind: DaemonSet
#          publishService:
#            enabled: false
#          extraArgs:
#            publish-status-address: 127.0.0.1
          tolerations:
            - effect: 'NoSchedule'
              operator: 'Exists'
        defaultBackend:
          enabled: false
          name: defaultbackend
          replicaCount: 2
          image:
            image: defaultbackend-amd64
            tag: '1.5'
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 65534
            runAsGroup: 65534
